### ISSUE TITLE
BoxB sequences not found in fischerella spp

### ISSUE THREAD

**Issue by phycologia** [nlabrad/motifsearch#20]
Can't figure out why this BoxB sequence couldn't be found in two Fischerella spp (order Nostocales, both spp have the same boxb sequence): TAGCATCTGAATGAAAATATTCAGGCTGCTG
Accession numbers for sequences: DQ786173.1 and DQ786171.1

**Comment by callmcgovern** [comment]
@phycologia - the new code ive been playing with for box b is under the branch "boxb testing". I just tried it with fischerella and it found boxB in both sequences. Ill change it on the test cases and we will merge this branch with the main branch soon
